[package]
name = "alone"
version = "0.1.0"
authors = ["QuantumEntangledAndy <sheepchaan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "*"
log =  "0.4"
pretty_env_logger = "0.4"
rust-bert = "*"
