[package]
name = "alone"
version = "0.1.0"
authors = ["QuantumEntangledAndy <sheepchaan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "*"
log =  "*"
err-derive = "*"
pretty_env_logger = "*"
rust-bert = "*"
tch = "*"
toml = "*"
uuid = { version = "*", features = ["v4"] }
crossbeam = "*"
serde = { version = "*", features = ["derive"] }
crossbeam-channel = "*"
validator = "*"
validator_derive = "*"
